# Generated by Django 4.0.4 on 2022-04-23 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('data_cadastro', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('data_servico', models.DateField()),
                ('hora_servico', models.CharField(max_length=20)),
                ('alimentacao', models.BooleanField(default=False)),
                ('combustivel', models.BooleanField(default=False)),
                ('enviado', models.BooleanField(default=False)),
                ('memoria_atend', models.FileField(blank=True, upload_to='memorias_atendimento/%Y/%m/%d/')),
                ('rota1', models.CharField(blank=True, max_length=200, null=True)),
                ('rota2', models.CharField(blank=True, max_length=200, null=True)),
                ('rota3', models.CharField(blank=True, max_length=200, null=True)),
                ('rota4', models.CharField(blank=True, max_length=200, null=True)),
                ('rota5', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'reembolso',
            },
        ),
    ]
